# Generated by Django 4.0.2 on 2022-02-26 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_topic_message_user_room_host_room_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
