# Generated by Django 4.0.2 on 2022-03-14 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_room_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='user',
            new_name='messager',
        ),
    ]
