# Generated by Django 4.0.2 on 2022-03-14 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_user_message_messager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='messager',
            new_name='user',
        ),
    ]
