# Generated by Django 4.0.2 on 2022-03-14 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_user_message_messager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='room',
            new_name='room_in',
        ),
    ]
